language: go

go:
    - 1.8
    - tip

script:
    - go test -race -v -bench=. github.com/dishuostec/kone/geoip
    - go test -race -v -bench=. github.com/dishuostec/kone/tcpip
    - go test -race -v -bench=. github.com/dishuostec/kone/k1
