version: '2.4'

services:
  app:
    image: golang:1.11-alpine
    container_name: golang_build
    volumes:
      - ~/Projects/go:/go
    working_dir: /go/src/github.com/dishuostec/kone
    entrypoint: ./build.sh
